---
title: "Philosophy of science"
format: pdf
editor: visual
---

#### *I følge Hume er det umulig å rasjonelt begrunne bruken av induksjon. Hva er argumentet for denne konklusjonen? Er det mulig å unngå Humes konklusjon? Begrunn svaret ditt.*

David Hume var en filosof som blant annet er kjent for sinex meninger knyttet til bruken av induksjon. Ifølge han er det umulig å rasjonelt begrunne bruken av induksjon. Begrunnelsen for dette går tilbake til bruken av ulike argumenter og uniformitetsprinsippet. Et argument er satt sammen av premisser og en konklusjon. Et argument kan være deduktivt gyldig som betyr at dersom premissene er sanne er det helt sikkert at konklusjonen også er sann, også kan et argument være induktivt sterkt som betyr at dersom premissene er sanne kan vi anta at konklusjonen mest sannsynlig er sann. Det finnes også gode og dårlige argumenter. Et godt argument må være enten deduktivt gyldig eller induktivt korrekt. Det er tre alternativer for hva som er gode premisser i et godt argument. Det første er at hvert premiss i argumentet må være en idérelasjon, som er påstander om hvordan ulike idéer er relatert til hverandre. Det andre er at premissene må støttes av empirisk evidens eller et sterkt argument. Empirisk evidens er kunnskap vi har på bakgrunn av hva vi har observert eller erfart tidligere. Og det tredje alternativet er at argumentet være ikke-sirkulært, som betyr at argumentasjonen ikke kan gå i sirkel. Dette betyr at et godt argument kan være godt på én måte, men et dårlig argument kan være dårlig på tre ulike måter. Uniformitetsprinsippet inngår i Humes begrunnelse for hvorfor man ikke rasjonelt kan begrunne bruken av induksjon, og går ut på at man antar at fremtiden vil utarte seg likt som fortiden. Hume stilte spørsmålstegn ved hvilket grunnlag vi har for å bruke tidligere observasjoner som grunnlag for å generalisere fremtiden. Uniformitetsprinsippet er en faktapåstand som ikke kan undersøkes empirisk. Den eneste måten å argumentere for uniformitetsprinsippet er at det alltid har stemt tidligere, så da vil det mest sannsynlig også stemme i morgen. Problemet med denne argumentasjonen er at det er et induktivt argument, og for at et induktivt argument skal være gyldig må man legge uniformitetsprinsippet til grunn. Dette argumentet blir derfor et sirkulært argument, altså et ikke-sterkt eller dårlig argument. Det er altså ikke mulig å argumentere for uniformitetsprinsippet uten å legge uniformitetsprinsippet til grunn. Likevel kan man argumentere for uniformitetsprinsippet ved bruk av praktisk rasjonalitet. Denne formen for rasjonalitet begrunnes med at du skal tro på noe dersom det gir deg et bedre liv. Det å tro på uniformitetsprinsippet kan gi deg et bedre liv ved at det for eksempel gjør det lettere å planlegge hverdagen, studere, jobbe og drive vitenskap. Dersom man hele tiden skulle tatt høyde for at absolutt ingen dag er lik og at selv om en teori er gyldig i dag vil den ikke nødvendigvis være gyldig i morgen, ville det gjort det vanskelig å leve, skapt mer stress i hverdagen og gjort det vanskelig å drive vitenskap. Vi er nødt til å ta utgangspunkt i uniformitetspinsippet for å ha både et velfungerende samfunn og privatliv, samtidig som det er viktig å være åpen for nye teorier da verden, samfunnet og vitenskapen er i konstant utvikling og at med tiden kan eldre teorier bli erstattet av nyutviklede teorier som baserer seg på ny kunnskap. Karl Popper var ikke imot at vi skal bruke våre tidligere erfaringer til å predikere fremtiden når det kommer til det daglige livet, men han mente at det ikke kan rasjonelt begrunnes og ikke hører hjemme i vitenskapen

#### *Gi en kort beskrivelse og forklaring av falsifikasjonisme. Presenter så ett problem med denne teorien. Tror du problemet kan løses? Begrunn svaret ditt.*

Falsifikajsonisme stammer fra Karl Popper og hans synspunkt på hva som skille vitenskap fra pseudovitenskap. Han var opptatt av å skille disse to og mente at en hypotese kun er vitenskapelig dersom den kan falsifiseres, hvis ikke er det pseudovitenskap. For at en påstand skal kunne falsifiseres må den kunne deduktivt utlede en prediksjon som kan empirisk sjekkes. Dette betyr ikke at alle falsifiserbare påstander er sanne, tvert imot kan falsifiserbare påstander også være usanne. Popper mente at en god falsifiserbar teori inneholdt presise og gjerne flere prediksjoner. Ifølge Popper kunne enten prediksjonene avkrefte teorien og dermed forkaste den, eller så kan prediksjonene gi grunnlag for å tro at teorien muligens er sann, men vi kan aldri være sikre. Å forkaste en teori basert på én undersøkelse kan virke som en veldig svart-hvit tankegang som kan by på utfordringer da verden ikke er svart-hvit. Det er også vanskelig å bedømme om det der prediksjonene som er feil, om teorien er feil, om det er feil i utførelsen av prosjektet, om det er målefeil, om det kan ha vært andre faktorer som har påvirket uten at man er klar over det, og mye mer. I et forsøk på å løse denne utfordringen kan man undersøke hvorvidt det er noe med argumentene som er årsaken til at teorien er falsifisert. Dette betyr at argumentene må bekreftes, hvilket ifølge falsifikasjonisme ikke er mulig da vi kun kan avkrefte. I tillegg krever bekreftelse induksjon noe Hume argumenterer sterkt for at ikke er mulig da man ifølge han ikke kan begrunne induksjon rasjonelt. En form for løsning på dette problemet kan være å inkludere signifikanstester eller p-verdier i forskning. I praksis betyr dette at p-verdien til en hypotese representerer sannsynligheten for at du vil observere det du observerte eller noe mer ekstremt gitt hypotesen. På denne måten kan man implementere en form for sannsynlighetsregning i en svart-hvit falsifikasjons-tankegang, og man vil kunne gi et svar på problemstillingen. Ikke nødvendiogvis et svar med to streker under, men et svar. Til tross for dette får man aldri bekreftet noe dersom man gjør slik Popper mente. Resultatene vil kun avkrefte men aldri bekrefte, og man kan i følge Popper aldri være sikker på om en teori stemmer. Det man sitter igjen med er en teori som enten er falsifisert eller ikke. Dersom en teori overlever mange undersøkelser eller tester, er den korroborert. Det finnes ingen løsning på induksjonsproblemet, men det betyr ikke at man ikke skal ta i bruk disse teoriene heller. Det man kan gjøre er å etterstrebe gode argumenter samtidig som man er åpen for at det ikke alltid finnes et ja- eller nei svar. Verden er kompleks og i mange tilfeller er det ikke to streker under svaret, men et samspill av mange faktorer og en sannsynlighet for at et utfall vil finne sted.
